version: "3.8"

services:
  db:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    networks:
      - backend_network
    volumes:
      - invoice_mysql_data:/var/lib/mysql

  project-a:
    container_name: project-a
    build:
      context: ./apps/project-a
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - backend_network
    links:
      - db

  project-b:
    container_name: project-b
    build:
      context: ./apps/project-b
    ports:
      - 3001:3001

  serverless:
    container_name: serverless
    build:
      context: ./apps/serverless
    ports:
      - 4000:4000

volumes:
  invoice_mysql_data:


networks:
  backend_network:
    driver: bridge
