version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  project-a:
    container_name: project-a
    build:
      context: ./apps/project-a
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  project-b:
    container_name: project-b
    build:
      context: ./apps/project-b
    ports:
      - 3001:3001

  serverless:
    container_name: serverless
    build:
      context: ./apps/serverless
    ports:
      - 4000:4000

volumes:
  db:
    driver: local
