service: serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'
